name: inspector-test.el
on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version: [ 27.1, 27.2, 28.1, 28.2, snapshot]

    steps:
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}
    - uses: actions/checkout@v2
    - name: run test for inspector.el
      run: |
        sh ./inspector-test.sh
