name: tree-inspector-test.el
on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version: [27.1,27.2,28.1,28.2,snapshot]


    steps:
          - uses: purcell/setup-emacs@master
            with:
              version: ${{ matrix.emacs_version }}

          - uses: actions/checkout@v2
          - name: run test for inspector.el
            run: |
                    NEEDED_PACKAGES="treeview"

                    INIT_PACKAGE_EL="(progn \
                    (require 'package) \
                    (push '(\"melpa\" . \"https://melpa.org/packages/\") package-archives) \
                    (package-initialize) \
                    (unless package-archive-contents \
                    (package-refresh-contents)) \
                    (dolist (pkg '(${NEEDED_PACKAGES})) \
                    (unless (package-installed-p pkg) \
                    (package-install pkg))))"

                    emacs -Q -batch \
                    --eval "$INIT_PACKAGE_EL"

                    emacs --batch -l ert -l tree-inspector.el -l tree-inspector-tests.el -f ert-run-tests-batch-and-exit
